import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, CalendarClock, Check, CheckCircle2, Clock3, Droplets, Leaf, MapPin, Phone, ShieldCheck, Sparkles, Star, Timer, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { QuoteForm } from "@/components/QuoteForm";
import { articles, services } from "@/lib/site-data";
import heroImage from "@/assets/primeclean-hero.jpg";
import carpetImage from "@/assets/carpet-before-after.jpg";
import mattressImage from "@/assets/mattress-cleaning.jpg";
import carImage from "@/assets/car-interior-cleaning.jpg";

export function HomePage() {
  return <>
    <section className="relative min-h-[670px] overflow-hidden bg-brand-deep text-primary-foreground">
      <img src={heroImage} width={1600} height={1008} alt="PrimeClean technician deep cleaning a sofa in Winnipeg" className="absolute inset-0 size-full object-cover object-[62%_center] opacity-65" />
      <div className="absolute inset-0 bg-linear-to-r from-brand-deep via-brand-deep/85 to-brand-deep/10" />
      <div className="page-shell relative flex min-h-[670px] items-center py-20"><div className="max-w-2xl">
        <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary-foreground/20 bg-primary-foreground/10 px-4 py-2 text-xs font-bold"><MapPin className="size-4 text-brand-bright" />LOCALLY OWNED IN WINNIPEG</div>
        <h1 className="text-4xl font-extrabold leading-[1.08] sm:text-5xl lg:text-7xl">Professional Carpet & Upholstery Cleaning in Winnipeg</h1>
        <p className="mt-6 max-w-xl text-base leading-7 text-primary-foreground/80 sm:text-lg">Remove stains, dirt, and odors. Deep extraction cleaning that removes allergens, dust mites, and bacteria for a fresher home and better sleep.</p>
        <div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/booking">Book Now <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline" className="border-primary-foreground/40 bg-primary-foreground/10 text-primary-foreground hover:bg-primary-foreground/20 hover:text-primary-foreground"><Link to="/contact">Get a Free Quote</Link></Button></div>
        <div className="mt-10 grid gap-3 text-sm font-semibold sm:grid-cols-3">{["Same-Day & Next-Day Available", "100% Satisfaction Guarantee", "Eco-Friendly Deep Extraction"].map((t) => <div key={t} className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-brand-bright" />{t}</div>)}</div>
      </div></div>
    </section>
    <section className="border-b bg-card"><div className="page-shell grid grid-cols-2 gap-px py-2 sm:grid-cols-3 lg:grid-cols-5">{services.map((s) => <Link key={s.slug} to="/services/$slug" params={{slug:s.slug}} className="flex items-center gap-3 rounded-lg p-4 transition hover:bg-accent"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-accent text-primary"><s.icon /></span><span className="text-sm font-bold">{s.short}</span></Link>)}</div></section>
    <SectionIntro eyebrow="Straightforward service" title="A cleaner home starts here" text="Choose the cleaning you need. Every appointment includes professional equipment, careful fiber assessment, and honest pricing." />
    <section className="page-shell -mt-12 grid gap-4 pb-24 md:grid-cols-2 lg:grid-cols-5">{services.map((s, i) => <article key={s.slug} className={`group overflow-hidden rounded-lg border bg-card shadow-sm transition hover:-translate-y-1 hover:shadow-xl ${i < 2 ? "lg:col-span-2" : ""}`}><img src={s.image} width={1200} height={912} loading="lazy" alt={s.name} className="aspect-[4/3] w-full object-cover"/><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-xl font-bold">{s.name}</h3><span className="whitespace-nowrap text-lg font-extrabold text-primary">From {s.price}</span></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{s.description}</p><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="flex items-center gap-1.5 text-xs font-semibold text-muted-foreground"><Clock3 className="size-4" />Est. {s.duration}</span><Button asChild size="sm"><Link to="/booking">Book Now</Link></Button></div></div></article>)}</section>
    <section className="section-pad bg-brand-deep text-primary-foreground"><div className="page-shell grid items-center gap-12 lg:grid-cols-2"><div><p className="eyebrow text-brand-bright">Visible proof</p><h2 className="mt-3 text-4xl font-extrabold sm:text-5xl">Real Results from Real Homes</h2><p className="mt-5 max-w-lg leading-7 text-primary-foreground/70">We remove deep stains, dirt, and odors using professional high-grade equipment.</p><div className="mt-8 grid grid-cols-3 gap-3">{["Deep stains", "Trapped odors", "Ground-in dirt"].map((x)=><div key={x} className="border-l-2 border-brand-bright pl-3 text-sm font-bold">{x}</div>)}</div></div><figure className="overflow-hidden rounded-lg bg-card shadow-2xl"><img src={carpetImage} width={1200} height={912} loading="lazy" alt="Carpet before and after professional cleaning" className="aspect-[4/3] w-full object-cover"/><figcaption className="grid grid-cols-2 bg-card py-3 text-center text-xs font-extrabold text-foreground"><span>BEFORE</span><span className="text-primary">AFTER</span></figcaption></figure></div></section>
    <section className="section-pad"><div className="page-shell"><div className="text-center"><p className="eyebrow">The PrimeClean difference</p><h2 className="mt-3 text-4xl font-extrabold">Why Winnipeg chooses us</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{([{icon:Droplets,title:"Deep Extraction Technology",text:"Professional equipment reaches deep into fibers."},{icon:Timer,title:"Fast Drying Times",text:"Efficient extraction means less disruption."},{icon:ShieldCheck,title:"Transparent Pricing",text:"Affordable service with no hidden fees."},{icon:CalendarClock,title:"Flexible Availability",text:"Same-day and next-day appointments in Winnipeg."}]).map(({icon:Icon,title,text})=><article key={title} className="rounded-lg border bg-card p-6"><span className="grid size-12 place-items-center rounded-lg bg-accent text-primary"><Icon /></span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section>
    <Reviews />
    <Articles />
    <section className="section-pad bg-accent"><div className="page-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Quick response</p><h2 className="mt-3 text-4xl font-extrabold sm:text-5xl">Get a Free Quote in Minutes</h2><p className="mt-4 text-lg text-muted-foreground">No obligation. Fast response. Affordable pricing.</p><a href="tel:+14312946727" className="mt-8 flex items-center gap-4 rounded-lg border bg-card p-4"><span className="grid size-11 place-items-center rounded-lg bg-primary text-primary-foreground"><Phone /></span><span><small className="block text-muted-foreground">Prefer to call?</small><strong>+1 (431) 294 6727</strong></span></a></div><div className="rounded-lg border bg-card p-6 shadow-xl sm:p-8"><QuoteForm compact /></div></div></section>
  </>;
}

function SectionIntro({eyebrow,title,text}:{eyebrow:string;title:string;text:string}) { return <section className="page-shell section-pad text-center"><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 text-4xl font-extrabold sm:text-5xl">{title}</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-muted-foreground">{text}</p></section>; }

function Reviews(){return <section className="section-pad bg-accent"><div className="page-shell"><SectionHeading eyebrow="Winnipeg homeowners" title="Trusted for cleaner, fresher spaces"/><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Maya R.","Couch Cleaning","The couch looks brand new and dried much faster than I expected."],["Daniel K.","Carpet Cleaning","Clear pricing, on time, and the high-traffic marks are finally gone."],["Priya S.","Mattress Cleaning","Professional, careful, and the room feels noticeably fresher."]].map(([name,service,quote])=><blockquote key={name} className="rounded-lg border bg-card p-6 shadow-sm"><div className="flex gap-1 text-secondary">{[1,2,3,4,5].map(x=><Star key={x} className="size-4 fill-current"/>)}</div><p className="mt-5 leading-7">“{quote}”</p><footer className="mt-5 border-t pt-4"><strong>{name}</strong><small className="ml-2 text-muted-foreground">Verified • {service}</small></footer></blockquote>)}</div></div></section>}

function SectionHeading({eyebrow,title}:{eyebrow:string;title:string}){return <div><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 text-4xl font-extrabold">{title}</h2></div>}

export function Articles(){return <section className="section-pad"><div className="page-shell"><div className="flex items-end justify-between"><SectionHeading eyebrow="Helpful advice" title="Fresh from the journal"/><Button asChild variant="outline" className="hidden sm:flex"><Link to="/blog">View all articles</Link></Button></div><div className="mt-10 grid gap-5 md:grid-cols-3">{articles.map(a=><article key={a.title} className="overflow-hidden rounded-lg border bg-card"><img src={a.image} width={1200} height={912} loading="lazy" alt="" className="aspect-[16/10] w-full object-cover"/><div className="p-5"><div className="text-xs font-bold text-primary">{a.category} · {a.time}</div><h3 className="mt-3 text-xl font-bold">{a.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{a.excerpt}</p></div></article>)}</div></div></section>}

export function PageHero({eyebrow,title,text,image=heroImage}:{eyebrow:string;title:string;text:string;image?:string}){return <section className="relative min-h-[440px] overflow-hidden bg-brand-deep text-primary-foreground"><img src={image} alt="" className="absolute inset-0 size-full object-cover opacity-35"/><div className="absolute inset-0 bg-linear-to-r from-brand-deep via-brand-deep/80 to-transparent"/><div className="page-shell relative flex min-h-[440px] items-center py-16"><div className="max-w-2xl"><p className="eyebrow text-brand-bright">{eyebrow}</p><h1 className="mt-4 text-4xl font-extrabold sm:text-6xl">{title}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-primary-foreground/75">{text}</p></div></div></section>}

export function AboutPage(){return <><PageHero eyebrow="Locally focused care" title="A higher standard of clean" text="Professional extraction cleaning for healthier, more comfortable Winnipeg homes."/><section className="section-pad"><div className="page-shell grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Our story & standards" title="Careful work. Honest service."/><p className="mt-5 leading-8 text-muted-foreground">PrimeClean Services helps local residents refresh the spaces they use every day. We pair commercial-grade extraction with careful fiber assessment, clear communication, and respect for your home.</p></div><div className="grid gap-3">{["Pre-inspection & Fiber Assessment","Eco-friendly Pre-spray & Agitation","Deep Steam Extraction & Odor Neutralization","Rapid Air Dry & Final Walkthrough"].map((s,i)=><div key={s} className="flex items-center gap-4 rounded-lg border bg-card p-5"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-primary font-bold text-primary-foreground">{i+1}</span><strong>{s}</strong></div>)}</div></div></section><section className="bg-brand-deep py-16 text-center text-primary-foreground"><div className="page-shell"><div className="flex justify-center gap-1 text-secondary">★★★★★</div><blockquote className="mx-auto mt-4 max-w-3xl font-display text-2xl font-bold">“Professional, careful, and the results were visible immediately.”</blockquote><p className="mt-3 text-sm text-primary-foreground/65">— Maya R., Winnipeg</p><Button asChild size="lg" className="mt-7"><Link to="/booking">Book an Appointment</Link></Button></div></section></>}

export function ServicesPage(){return <><PageHero eyebrow="Five specialty services" title="Deep cleaning, built around your home" text="Transparent starting prices, professional equipment, and flexible Winnipeg appointments."/><section className="section-pad"><div className="page-shell grid gap-5 md:grid-cols-2">{services.map(s=><article key={s.slug} className="grid overflow-hidden rounded-lg border bg-card sm:grid-cols-[180px_1fr]"><img src={s.image} alt={s.name} className="h-full min-h-48 w-full object-cover"/><div className="p-6"><div className="flex justify-between gap-3"><h2 className="text-2xl font-bold">{s.name}</h2><strong className="text-primary">From {s.price}</strong></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{s.description}</p><span className="mt-4 flex items-center gap-2 text-sm"><Clock3 className="size-4 text-primary"/>Est. {s.duration}</span><div className="mt-5 flex gap-2"><Button asChild><Link to="/booking">Book Now</Link></Button><Button asChild variant="outline"><Link to="/services/$slug" params={{slug:s.slug}}>Learn More</Link></Button></div></div></article>)}</div></section></>}

export function ServiceDetailPage({slug}:{slug:string}){const service=services.find(s=>s.slug===slug) ?? services[0];return <><PageHero eyebrow={`From ${service.price} · Est. ${service.duration}`} title={service.name} text={service.description} image={service.image}/><section className="section-pad"><div className="page-shell grid gap-12 lg:grid-cols-[1fr_380px]"><div><SectionHeading eyebrow="Every appointment" title="What’s included"/><ul className="mt-7 grid gap-4 sm:grid-cols-2">{["Pre-inspection and fiber check","Targeted stain treatment","Professional deep extraction","Deodorizing and sanitizing","High-powered moisture removal","Final quality walkthrough"].map(x=><li key={x} className="flex gap-3 rounded-lg border bg-card p-4"><Check className="size-5 text-success"/>{x}</li>)}</ul><h2 className="mt-14 text-3xl font-bold">Frequently asked questions</h2><div className="mt-5 grid gap-3">{["How long will it take to dry?","Are your products family-friendly?","Can you remove every stain?"].map(q=><details key={q} className="rounded-lg border bg-card p-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">Drying and treatment results vary by material and condition. We assess every item before work begins and explain what to expect.</p></details>)}</div></div><aside className="h-fit rounded-lg border bg-accent p-7 lg:sticky lg:top-28"><p className="text-sm font-bold text-primary">STARTING AT</p><div className="mt-2 font-display text-5xl font-extrabold">{service.price}</div><p className="mt-3 text-sm text-muted-foreground">Professional service • Est. {service.duration}</p><Button asChild size="lg" className="mt-6 w-full"><Link to="/booking">Book this service</Link></Button><a href="tel:+14312946727" className="mt-4 block text-center text-sm font-bold">or call +1 (431) 294 6727</a></aside></div></section></>}

export function GalleryPage(){const [filter,setFilter]=useState("All");const items=[{n:"Couch Cleaning",i:heroImage},{n:"Carpet Extraction",i:carpetImage},{n:"Mattresses",i:mattressImage},{n:"Auto Detailing",i:carImage},{n:"Carpet Extraction",i:carpetImage},{n:"Couch Cleaning",i:heroImage}];return <><PageHero eyebrow="Our portfolio" title="Our Work in Action across Winnipeg" text="A closer look at the fibers, fabrics, and interiors we help restore." image={carpetImage}/><section className="section-pad"><div className="page-shell"><div className="flex flex-wrap gap-2">{["All","Couch Cleaning","Carpet Extraction","Mattresses","Auto Detailing"].map(f=><Button key={f} variant={filter===f?"default":"outline"} onClick={()=>setFilter(f)}>{f}</Button>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.filter(x=>filter==="All"||x.n===filter).map((x,i)=><figure key={`${x.n}-${i}`} className="group relative overflow-hidden rounded-lg"><img src={x.i} alt={x.n} className="aspect-square w-full object-cover transition duration-500 group-hover:scale-105"/><figcaption className="absolute inset-x-0 bottom-0 bg-brand-deep/85 p-4 font-bold text-primary-foreground">{x.n}</figcaption></figure>)}</div></div></section></>}

export function BlogPage(){return <><PageHero eyebrow="Cleaning advice" title="A cleaner home, explained" text="Practical stain, fiber care, and home hygiene guidance from the PrimeClean team." image={mattressImage}/><Articles /></>}

export function ContactPage({booking=false}:{booking?:boolean}){return <><PageHero eyebrow={booking?"Reserve your appointment":"Fast, no-obligation quote"} title={booking?"Book PrimeClean":"Let’s talk about your space"} text="Same-day and next-day appointments are available across Winnipeg."/><section className="section-pad"><div className="page-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeading eyebrow="Contact details" title="We’re ready when you are"/><div className="mt-7 grid gap-4">{([{icon:Phone,label:"Phone",value:"+1 (431) 294 6727"},{icon:Sparkles,label:"Email",value:"primeclean.ca@gmail.com"},{icon:MapPin,label:"Service Area",value:"Winnipeg, Manitoba, Canada"},{icon:Zap,label:"Availability",value:"Same-day & Next-day Appointments Available"}]).map(({icon:Icon,label,value})=><div key={label} className="flex gap-4 rounded-lg border bg-card p-5"><span className="grid size-11 shrink-0 place-items-center rounded-lg bg-accent text-primary"><Icon/></span><span><small className="text-muted-foreground">{label}</small><strong className="block mt-1">{value}</strong></span></div>)}</div></div><div className="rounded-lg border bg-card p-6 shadow-xl sm:p-8"><QuoteForm /></div></div></section></>}

export function AccountPage(){return <><PageHero eyebrow="My account" title="Welcome back" text="Review your appointment details and keep your contact information current."/><section className="page-shell section-pad"><div className="mx-auto max-w-md rounded-lg border bg-card p-8 shadow-lg"><h2 className="text-2xl font-bold">Log in to your account</h2><div className="mt-6 grid gap-4"><label className="grid gap-2 text-sm font-bold">Email<input type="email" className="h-12 rounded-lg border px-4"/></label><label className="grid gap-2 text-sm font-bold">Password<input type="password" className="h-12 rounded-lg border px-4"/></label><Button size="lg">Log In</Button></div></div></section></>}

export function LegalPage(){return <section className="page-shell section-pad max-w-3xl"><p className="eyebrow">PrimeClean Services</p><h1 className="mt-3 text-5xl font-extrabold">Terms & Privacy</h1><div className="mt-10 grid gap-8 leading-8 text-muted-foreground"><p>Information submitted through our quote and booking forms is used to respond to your service request and coordinate appointments.</p><p>Service timing and final pricing may vary based on item size, material, condition, and access. We confirm the scope before work begins.</p><p>Questions can be directed to primeclean.ca@gmail.com or +1 (431) 294 6727.</p></div></section>}